### ISSUE TITLE
bug: update GeometryOps compat

### ISSUE THREAD

**Issue by juliasloan25** [MakieOrg/GeoMakie.jl#286]
We've been seeing a few failures in downstream CliMA packages today (e.g. [ClimaCoupler.jl GHA](https://github.com/CliMA/ClimaCoupler.jl/actions/runs/11785000744/job/32825328496?pr=1078)), which I believe is due to the following compat issues:

ExactPredicates was added to GeometryOps.jl in [v0.1.6](https://github.com/JuliaGeo/GeometryOps.jl/compare/v0.1.5...v0.1.6). GeoMakie.jl started using this feature in their release [0.7.6](https://github.com/MakieOrg/GeoMakie.jl/compare/v0.7.5...v0.7.6) earlier today, but didn't update the GeometryOps compat so it's still at v0.1.4. To maintain compat correctness, it should have been updated to 0.1.6 [here](https://github.com/MakieOrg/GeoMakie.jl/blob/2414182648279cd0ad5a854fb814b5af36fcf170/Project.toml#L34).

I would open a PR to make the change myself, but it seems I don't have access rights to this repo. Would it be possible to make another patch release including this fix?

**Comment by juliasloan25** [comment]
cc @asinghvi17

**Comment by asinghvi17** [comment]
Thanks for the ping, forgot that we haven't done many releases of GeometryOps since ExactPredicates 😅.

New release v0.7.8 is out with bumped compatibility.  But I do wonder what is keeping GeometryOps versions low on that CI?

We should probably have downgrade CI here as well.  I'll add the script but may not have much time to debug.
